/**
 * Best-effort 3-digit Swedish postal-code → area lookup.
 *
 * Used to make the calculator result feel personal — *"En villa i Älta"*
 * beats *"En villa i 138 36"*. Falls back to the broad region by first
 * digit when the prefix is unknown, so every input resolves to something
 * usable for the copy. Replace with a verified public dataset when the
 * accuracy bar rises (e.g., for production analytics or filtering).
 */

export type PostalArea = {
  /** Display name used in the result copy ("Älta", "Storstockholm"). */
  city: string;
  /** Kommun if known. Optional. */
  kommun?: string;
  /** Broader region name. Always present. */
  region: string;
};

/* ---------- 3-digit prefix table ----------
   Curated for major population centres only — confidence over coverage.
   Unknown prefixes fall back to the regional table below. */
const PREFIX_TABLE: Record<string, PostalArea> = {
  // ----- Storstockholm -----
  "100": { city: "Stockholm", kommun: "Stockholm", region: "Stockholms län" },
  "111": { city: "Stockholm city", kommun: "Stockholm", region: "Stockholms län" },
  "112": { city: "Kungsholmen", kommun: "Stockholm", region: "Stockholms län" },
  "113": { city: "Vasastan", kommun: "Stockholm", region: "Stockholms län" },
  "114": { city: "Östermalm", kommun: "Stockholm", region: "Stockholms län" },
  "115": { city: "Östermalm", kommun: "Stockholm", region: "Stockholms län" },
  "116": { city: "Södermalm", kommun: "Stockholm", region: "Stockholms län" },
  "117": { city: "Södermalm", kommun: "Stockholm", region: "Stockholms län" },
  "118": { city: "Södermalm", kommun: "Stockholm", region: "Stockholms län" },
  "120": { city: "Årsta", kommun: "Stockholm", region: "Stockholms län" },
  "121": { city: "Johanneshov", kommun: "Stockholm", region: "Stockholms län" },
  "122": { city: "Enskede", kommun: "Stockholm", region: "Stockholms län" },
  "123": { city: "Farsta", kommun: "Stockholm", region: "Stockholms län" },
  "124": { city: "Bandhagen", kommun: "Stockholm", region: "Stockholms län" },
  "125": { city: "Älvsjö", kommun: "Stockholm", region: "Stockholms län" },
  "126": { city: "Hägersten", kommun: "Stockholm", region: "Stockholms län" },
  "127": { city: "Skärholmen", kommun: "Stockholm", region: "Stockholms län" },
  "128": { city: "Bagarmossen", kommun: "Stockholm", region: "Stockholms län" },
  "129": { city: "Hägersten", kommun: "Stockholm", region: "Stockholms län" },
  "131": { city: "Nacka", kommun: "Nacka", region: "Stockholms län" },
  "132": { city: "Saltsjö-Boo", kommun: "Nacka", region: "Stockholms län" },
  "133": { city: "Saltsjöbaden", kommun: "Nacka", region: "Stockholms län" },
  "134": { city: "Gustavsberg", kommun: "Värmdö", region: "Stockholms län" },
  "135": { city: "Tyresö", kommun: "Tyresö", region: "Stockholms län" },
  "136": { city: "Handen", kommun: "Haninge", region: "Stockholms län" },
  "137": { city: "Västerhaninge", kommun: "Haninge", region: "Stockholms län" },
  "138": { city: "Älta", kommun: "Nacka", region: "Stockholms län" },
  "139": { city: "Värmdö", kommun: "Värmdö", region: "Stockholms län" },
  "141": { city: "Huddinge", kommun: "Huddinge", region: "Stockholms län" },
  "142": { city: "Trångsund", kommun: "Huddinge", region: "Stockholms län" },
  "143": { city: "Vårby", kommun: "Huddinge", region: "Stockholms län" },
  "144": { city: "Rönninge", kommun: "Salem", region: "Stockholms län" },
  "145": { city: "Norsborg", kommun: "Botkyrka", region: "Stockholms län" },
  "146": { city: "Tullinge", kommun: "Botkyrka", region: "Stockholms län" },
  "147": { city: "Tumba", kommun: "Botkyrka", region: "Stockholms län" },
  "148": { city: "Södertälje", kommun: "Södertälje", region: "Stockholms län" },
  "149": { city: "Nynäshamn", kommun: "Nynäshamn", region: "Stockholms län" },
  "151": { city: "Södertälje", kommun: "Södertälje", region: "Stockholms län" },
  "152": { city: "Södertälje", kommun: "Södertälje", region: "Stockholms län" },
  "168": { city: "Bromma", kommun: "Stockholm", region: "Stockholms län" },
  "169": { city: "Solna", kommun: "Solna", region: "Stockholms län" },
  "170": { city: "Solna", kommun: "Solna", region: "Stockholms län" },
  "171": { city: "Solna", kommun: "Solna", region: "Stockholms län" },
  "172": { city: "Sundbyberg", kommun: "Sundbyberg", region: "Stockholms län" },
  "174": { city: "Sundbyberg", kommun: "Sundbyberg", region: "Stockholms län" },
  "175": { city: "Järfälla", kommun: "Järfälla", region: "Stockholms län" },
  "176": { city: "Järfälla", kommun: "Järfälla", region: "Stockholms län" },
  "177": { city: "Järfälla", kommun: "Järfälla", region: "Stockholms län" },
  "181": { city: "Lidingö", kommun: "Lidingö", region: "Stockholms län" },
  "182": { city: "Danderyd", kommun: "Danderyd", region: "Stockholms län" },
  "183": { city: "Täby", kommun: "Täby", region: "Stockholms län" },
  "184": { city: "Åkersberga", kommun: "Österåker", region: "Stockholms län" },
  "185": { city: "Vaxholm", kommun: "Vaxholm", region: "Stockholms län" },
  "186": { city: "Vallentuna", kommun: "Vallentuna", region: "Stockholms län" },
  "187": { city: "Täby", kommun: "Täby", region: "Stockholms län" },
  "191": { city: "Sollentuna", kommun: "Sollentuna", region: "Stockholms län" },
  "192": { city: "Sollentuna", kommun: "Sollentuna", region: "Stockholms län" },
  "194": { city: "Upplands Väsby", kommun: "Upplands Väsby", region: "Stockholms län" },
  "195": { city: "Märsta", kommun: "Sigtuna", region: "Stockholms län" },
  "196": { city: "Kungsängen", kommun: "Upplands-Bro", region: "Stockholms län" },
  "197": { city: "Bro", kommun: "Upplands-Bro", region: "Stockholms län" },

  // ----- Skåne -----
  "200": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "211": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "212": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "213": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "214": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "215": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "216": { city: "Limhamn", kommun: "Malmö", region: "Skåne" },
  "217": { city: "Malmö", kommun: "Malmö", region: "Skåne" },
  "218": { city: "Bunkeflostrand", kommun: "Malmö", region: "Skåne" },
  "220": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "222": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "223": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "224": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "225": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "226": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "227": { city: "Lund", kommun: "Lund", region: "Skåne" },
  "230": { city: "Klågerup", kommun: "Svedala", region: "Skåne" },
  "231": { city: "Trelleborg", kommun: "Trelleborg", region: "Skåne" },
  "232": { city: "Arlöv", kommun: "Burlöv", region: "Skåne" },
  "233": { city: "Svedala", kommun: "Svedala", region: "Skåne" },
  "234": { city: "Lomma", kommun: "Lomma", region: "Skåne" },
  "235": { city: "Vellinge", kommun: "Vellinge", region: "Skåne" },
  "236": { city: "Höllviken", kommun: "Vellinge", region: "Skåne" },
  "237": { city: "Bjärred", kommun: "Lomma", region: "Skåne" },
  "240": { city: "Eslöv", kommun: "Eslöv", region: "Skåne" },
  "241": { city: "Eslöv", kommun: "Eslöv", region: "Skåne" },
  "243": { city: "Höör", kommun: "Höör", region: "Skåne" },
  "244": { city: "Kävlinge", kommun: "Kävlinge", region: "Skåne" },
  "245": { city: "Staffanstorp", kommun: "Staffanstorp", region: "Skåne" },
  "246": { city: "Löddeköpinge", kommun: "Kävlinge", region: "Skåne" },
  "250": { city: "Helsingborg", kommun: "Helsingborg", region: "Skåne" },
  "252": { city: "Helsingborg", kommun: "Helsingborg", region: "Skåne" },
  "253": { city: "Helsingborg", kommun: "Helsingborg", region: "Skåne" },
  "254": { city: "Helsingborg", kommun: "Helsingborg", region: "Skåne" },
  "255": { city: "Helsingborg", kommun: "Helsingborg", region: "Skåne" },
  "260": { city: "Höganäs", kommun: "Höganäs", region: "Skåne" },
  "261": { city: "Landskrona", kommun: "Landskrona", region: "Skåne" },
  "262": { city: "Ängelholm", kommun: "Ängelholm", region: "Skåne" },
  "263": { city: "Höganäs", kommun: "Höganäs", region: "Skåne" },
  "264": { city: "Klippan", kommun: "Klippan", region: "Skåne" },
  "265": { city: "Åstorp", kommun: "Åstorp", region: "Skåne" },
  "270": { city: "Skurup", kommun: "Skurup", region: "Skåne" },
  "271": { city: "Ystad", kommun: "Ystad", region: "Skåne" },
  "272": { city: "Simrishamn", kommun: "Simrishamn", region: "Skåne" },
  "273": { city: "Tomelilla", kommun: "Tomelilla", region: "Skåne" },
  "280": { city: "Hässleholm", kommun: "Hässleholm", region: "Skåne" },
  "281": { city: "Hässleholm", kommun: "Hässleholm", region: "Skåne" },
  "291": { city: "Kristianstad", kommun: "Kristianstad", region: "Skåne" },
  "294": { city: "Sölvesborg", kommun: "Sölvesborg", region: "Blekinge" },
  "296": { city: "Åhus", kommun: "Kristianstad", region: "Skåne" },

  // ----- Halland & nordvästra Småland -----
  "300": { city: "Halmstad", kommun: "Halmstad", region: "Halland" },
  "301": { city: "Halmstad", kommun: "Halmstad", region: "Halland" },
  "302": { city: "Halmstad", kommun: "Halmstad", region: "Halland" },
  "310": { city: "Hyltebruk", kommun: "Hylte", region: "Halland" },
  "311": { city: "Falkenberg", kommun: "Falkenberg", region: "Halland" },
  "312": { city: "Laholm", kommun: "Laholm", region: "Halland" },
  "313": { city: "Oskarström", kommun: "Halmstad", region: "Halland" },

  // ----- Småland & Blekinge -----
  "330": { city: "Smålandsstenar", kommun: "Gislaved", region: "Småland" },
  "331": { city: "Värnamo", kommun: "Värnamo", region: "Småland" },
  "332": { city: "Gislaved", kommun: "Gislaved", region: "Småland" },
  "333": { city: "Anderstorp", kommun: "Gislaved", region: "Småland" },
  "335": { city: "Gnosjö", kommun: "Gnosjö", region: "Småland" },
  "340": { city: "Vislanda", kommun: "Alvesta", region: "Småland" },
  "341": { city: "Ljungby", kommun: "Ljungby", region: "Småland" },
  "342": { city: "Älmhult", kommun: "Älmhult", region: "Småland" },
  "343": { city: "Älmhult", kommun: "Älmhult", region: "Småland" },
  "350": { city: "Växjö", kommun: "Växjö", region: "Småland" },
  "352": { city: "Växjö", kommun: "Växjö", region: "Småland" },
  "355": { city: "Växjö", kommun: "Växjö", region: "Småland" },
  "360": { city: "Lessebo", kommun: "Lessebo", region: "Småland" },
  "361": { city: "Emmaboda", kommun: "Emmaboda", region: "Småland" },
  "370": { city: "Karlskrona", kommun: "Karlskrona", region: "Blekinge" },
  "371": { city: "Karlskrona", kommun: "Karlskrona", region: "Blekinge" },
  "372": { city: "Ronneby", kommun: "Ronneby", region: "Blekinge" },
  "374": { city: "Karlshamn", kommun: "Karlshamn", region: "Blekinge" },
  "380": { city: "Mörbylånga", kommun: "Mörbylånga", region: "Kalmar län" },
  "381": { city: "Kalmar", kommun: "Kalmar", region: "Kalmar län" },
  "382": { city: "Nybro", kommun: "Nybro", region: "Kalmar län" },
  "383": { city: "Mönsterås", kommun: "Mönsterås", region: "Kalmar län" },
  "385": { city: "Torsås", kommun: "Torsås", region: "Kalmar län" },
  "386": { city: "Färjestaden", kommun: "Mörbylånga", region: "Kalmar län" },
  "387": { city: "Borgholm", kommun: "Borgholm", region: "Kalmar län" },
  "388": { city: "Ljungbyholm", kommun: "Kalmar", region: "Kalmar län" },
  "390": { city: "Kalmar", kommun: "Kalmar", region: "Kalmar län" },
  "392": { city: "Kalmar", kommun: "Kalmar", region: "Kalmar län" },
  "393": { city: "Kalmar", kommun: "Kalmar", region: "Kalmar län" },
  "394": { city: "Kalmar", kommun: "Kalmar", region: "Kalmar län" },

  // ----- Storgöteborg -----
  "400": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "411": { city: "Göteborg city", kommun: "Göteborg", region: "Västra Götaland" },
  "412": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "413": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "414": { city: "Majorna", kommun: "Göteborg", region: "Västra Götaland" },
  "415": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "416": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "417": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "418": { city: "Göteborg", kommun: "Göteborg", region: "Västra Götaland" },
  "421": { city: "Västra Frölunda", kommun: "Göteborg", region: "Västra Götaland" },
  "422": { city: "Hisings Backa", kommun: "Göteborg", region: "Västra Götaland" },
  "423": { city: "Torslanda", kommun: "Göteborg", region: "Västra Götaland" },
  "424": { city: "Angered", kommun: "Göteborg", region: "Västra Götaland" },
  "425": { city: "Hisings Kärra", kommun: "Göteborg", region: "Västra Götaland" },
  "426": { city: "Västra Frölunda", kommun: "Göteborg", region: "Västra Götaland" },
  "427": { city: "Billdal", kommun: "Göteborg", region: "Västra Götaland" },
  "428": { city: "Kållered", kommun: "Mölndal", region: "Västra Götaland" },
  "429": { city: "Särö", kommun: "Kungsbacka", region: "Halland" },
  "431": { city: "Mölndal", kommun: "Mölndal", region: "Västra Götaland" },
  "433": { city: "Partille", kommun: "Partille", region: "Västra Götaland" },
  "434": { city: "Kungsbacka", kommun: "Kungsbacka", region: "Halland" },
  "435": { city: "Mölnlycke", kommun: "Härryda", region: "Västra Götaland" },
  "436": { city: "Askim", kommun: "Göteborg", region: "Västra Götaland" },
  "437": { city: "Lindome", kommun: "Mölndal", region: "Västra Götaland" },
  "438": { city: "Landvetter", kommun: "Härryda", region: "Västra Götaland" },
  "442": { city: "Kungälv", kommun: "Kungälv", region: "Västra Götaland" },
  "443": { city: "Lerum", kommun: "Lerum", region: "Västra Götaland" },
  "444": { city: "Stenungsund", kommun: "Stenungsund", region: "Västra Götaland" },
  "451": { city: "Uddevalla", kommun: "Uddevalla", region: "Västra Götaland" },
  "452": { city: "Strömstad", kommun: "Strömstad", region: "Västra Götaland" },
  "453": { city: "Lysekil", kommun: "Lysekil", region: "Västra Götaland" },
  "461": { city: "Trollhättan", kommun: "Trollhättan", region: "Västra Götaland" },
  "462": { city: "Vänersborg", kommun: "Vänersborg", region: "Västra Götaland" },

  // ----- Västergötland & Sjuhärad -----
  "501": { city: "Borås", kommun: "Borås", region: "Västra Götaland" },
  "503": { city: "Borås", kommun: "Borås", region: "Västra Götaland" },
  "511": { city: "Kinna", kommun: "Mark", region: "Västra Götaland" },
  "521": { city: "Falköping", kommun: "Falköping", region: "Västra Götaland" },
  "531": { city: "Lidköping", kommun: "Lidköping", region: "Västra Götaland" },
  "541": { city: "Skövde", kommun: "Skövde", region: "Västra Götaland" },
  "549": { city: "Tibro", kommun: "Tibro", region: "Västra Götaland" },
  "551": { city: "Jönköping", kommun: "Jönköping", region: "Småland" },
  "553": { city: "Jönköping", kommun: "Jönköping", region: "Småland" },
  "554": { city: "Jönköping", kommun: "Jönköping", region: "Småland" },
  "555": { city: "Jönköping", kommun: "Jönköping", region: "Småland" },
  "556": { city: "Jönköping", kommun: "Jönköping", region: "Småland" },
  "560": { city: "Tenhult", kommun: "Jönköping", region: "Småland" },
  "561": { city: "Huskvarna", kommun: "Jönköping", region: "Småland" },
  "562": { city: "Norrahammar", kommun: "Jönköping", region: "Småland" },
  "564": { city: "Bankeryd", kommun: "Jönköping", region: "Småland" },
  "566": { city: "Habo", kommun: "Habo", region: "Västra Götaland" },
  "568": { city: "Skillingaryd", kommun: "Vaggeryd", region: "Småland" },
  "571": { city: "Nässjö", kommun: "Nässjö", region: "Småland" },
  "574": { city: "Vetlanda", kommun: "Vetlanda", region: "Småland" },
  "575": { city: "Eksjö", kommun: "Eksjö", region: "Småland" },
  "576": { city: "Sävsjö", kommun: "Sävsjö", region: "Småland" },
  "577": { city: "Hultsfred", kommun: "Hultsfred", region: "Kalmar län" },
  "578": { city: "Aneby", kommun: "Aneby", region: "Småland" },

  // ----- Östergötland -----
  "581": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "582": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "583": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "584": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "585": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "586": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "587": { city: "Linköping", kommun: "Linköping", region: "Östergötland" },
  "590": { city: "Mjölby", kommun: "Mjölby", region: "Östergötland" },
  "591": { city: "Motala", kommun: "Motala", region: "Östergötland" },
  "592": { city: "Vadstena", kommun: "Vadstena", region: "Östergötland" },
  "597": { city: "Åtvidaberg", kommun: "Åtvidaberg", region: "Östergötland" },
  "598": { city: "Vimmerby", kommun: "Vimmerby", region: "Kalmar län" },
  "601": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "602": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "603": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "604": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "605": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "606": { city: "Norrköping", kommun: "Norrköping", region: "Östergötland" },
  "610": { city: "Söderköping", kommun: "Söderköping", region: "Östergötland" },
  "611": { city: "Nyköping", kommun: "Nyköping", region: "Södermanland" },
  "612": { city: "Finspång", kommun: "Finspång", region: "Östergötland" },
  "613": { city: "Oxelösund", kommun: "Oxelösund", region: "Södermanland" },
  "614": { city: "Söderköping", kommun: "Söderköping", region: "Östergötland" },
  "615": { city: "Valdemarsvik", kommun: "Valdemarsvik", region: "Östergötland" },
  "616": { city: "Åby", kommun: "Norrköping", region: "Östergötland" },
  "617": { city: "Skärblacka", kommun: "Norrköping", region: "Östergötland" },
  "618": { city: "Kolmården", kommun: "Norrköping", region: "Östergötland" },
  "619": { city: "Trosa", kommun: "Trosa", region: "Södermanland" },

  // ----- Gotland -----
  "621": { city: "Visby", kommun: "Gotland", region: "Gotland" },
  "622": { city: "Romakloster", kommun: "Gotland", region: "Gotland" },
  "623": { city: "Hemse", kommun: "Gotland", region: "Gotland" },
  "624": { city: "Slite", kommun: "Gotland", region: "Gotland" },

  // ----- Mellansverige -----
  "631": { city: "Eskilstuna", kommun: "Eskilstuna", region: "Södermanland" },
  "632": { city: "Eskilstuna", kommun: "Eskilstuna", region: "Södermanland" },
  "633": { city: "Eskilstuna", kommun: "Eskilstuna", region: "Södermanland" },
  "635": { city: "Torshälla", kommun: "Eskilstuna", region: "Södermanland" },
  "640": { city: "Strängnäs", kommun: "Strängnäs", region: "Södermanland" },
  "641": { city: "Katrineholm", kommun: "Katrineholm", region: "Södermanland" },
  "642": { city: "Flen", kommun: "Flen", region: "Södermanland" },
  "643": { city: "Vingåker", kommun: "Vingåker", region: "Södermanland" },
  "645": { city: "Strängnäs", kommun: "Strängnäs", region: "Södermanland" },
  "647": { city: "Mariefred", kommun: "Strängnäs", region: "Södermanland" },
  "651": { city: "Karlstad", kommun: "Karlstad", region: "Värmland" },
  "652": { city: "Karlstad", kommun: "Karlstad", region: "Värmland" },
  "653": { city: "Karlstad", kommun: "Karlstad", region: "Värmland" },
  "654": { city: "Karlstad", kommun: "Karlstad", region: "Värmland" },
  "656": { city: "Skoghall", kommun: "Hammarö", region: "Värmland" },
  "657": { city: "Karlstad", kommun: "Karlstad", region: "Värmland" },
  "660": { city: "Molkom", kommun: "Karlstad", region: "Värmland" },
  "661": { city: "Säffle", kommun: "Säffle", region: "Värmland" },
  "662": { city: "Åmål", kommun: "Åmål", region: "Västra Götaland" },
  "663": { city: "Hammarö", kommun: "Hammarö", region: "Värmland" },
  "664": { city: "Grums", kommun: "Grums", region: "Värmland" },
  "665": { city: "Kil", kommun: "Kil", region: "Värmland" },
  "667": { city: "Forshaga", kommun: "Forshaga", region: "Värmland" },
  "669": { city: "Deje", kommun: "Forshaga", region: "Värmland" },
  "671": { city: "Arvika", kommun: "Arvika", region: "Värmland" },
  "672": { city: "Årjäng", kommun: "Årjäng", region: "Värmland" },
  "681": { city: "Kristinehamn", kommun: "Kristinehamn", region: "Värmland" },
  "682": { city: "Filipstad", kommun: "Filipstad", region: "Värmland" },
  "683": { city: "Hagfors", kommun: "Hagfors", region: "Värmland" },
  "684": { city: "Munkfors", kommun: "Munkfors", region: "Värmland" },
  "685": { city: "Torsby", kommun: "Torsby", region: "Värmland" },
  "691": { city: "Karlskoga", kommun: "Karlskoga", region: "Örebro län" },
  "692": { city: "Kumla", kommun: "Kumla", region: "Örebro län" },
  "693": { city: "Degerfors", kommun: "Degerfors", region: "Örebro län" },

  // ----- Närke, Västmanland, Dalarna -----
  "701": { city: "Örebro", kommun: "Örebro", region: "Örebro län" },
  "702": { city: "Örebro", kommun: "Örebro", region: "Örebro län" },
  "703": { city: "Örebro", kommun: "Örebro", region: "Örebro län" },
  "704": { city: "Örebro", kommun: "Örebro", region: "Örebro län" },
  "705": { city: "Örebro", kommun: "Örebro", region: "Örebro län" },
  "711": { city: "Lindesberg", kommun: "Lindesberg", region: "Örebro län" },
  "712": { city: "Hällefors", kommun: "Hällefors", region: "Örebro län" },
  "713": { city: "Nora", kommun: "Nora", region: "Örebro län" },
  "715": { city: "Odensbacken", kommun: "Örebro", region: "Örebro län" },
  "718": { city: "Frövi", kommun: "Lindesberg", region: "Örebro län" },
  "721": { city: "Västerås", kommun: "Västerås", region: "Västmanland" },
  "722": { city: "Västerås", kommun: "Västerås", region: "Västmanland" },
  "723": { city: "Västerås", kommun: "Västerås", region: "Västmanland" },
  "724": { city: "Västerås", kommun: "Västerås", region: "Västmanland" },
  "725": { city: "Västerås", kommun: "Västerås", region: "Västmanland" },
  "731": { city: "Köping", kommun: "Köping", region: "Västmanland" },
  "732": { city: "Arboga", kommun: "Arboga", region: "Västmanland" },
  "733": { city: "Sala", kommun: "Sala", region: "Västmanland" },
  "734": { city: "Hallstahammar", kommun: "Hallstahammar", region: "Västmanland" },
  "737": { city: "Fagersta", kommun: "Fagersta", region: "Västmanland" },
  "738": { city: "Norberg", kommun: "Norberg", region: "Västmanland" },
  "741": { city: "Knivsta", kommun: "Knivsta", region: "Uppsala län" },
  "743": { city: "Storvreta", kommun: "Uppsala", region: "Uppsala län" },
  "744": { city: "Heby", kommun: "Heby", region: "Uppsala län" },
  "745": { city: "Enköping", kommun: "Enköping", region: "Uppsala län" },
  "746": { city: "Bålsta", kommun: "Håbo", region: "Uppsala län" },
  "747": { city: "Alunda", kommun: "Östhammar", region: "Uppsala län" },
  "748": { city: "Österbybruk", kommun: "Östhammar", region: "Uppsala län" },
  "751": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "752": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "753": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "754": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "755": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "756": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "757": { city: "Uppsala", kommun: "Uppsala", region: "Uppsala län" },
  "761": { city: "Norrtälje", kommun: "Norrtälje", region: "Stockholms län" },
  "763": { city: "Hallstavik", kommun: "Norrtälje", region: "Stockholms län" },
  "764": { city: "Rimbo", kommun: "Norrtälje", region: "Stockholms län" },
  "771": { city: "Ludvika", kommun: "Ludvika", region: "Dalarna" },
  "772": { city: "Grängesberg", kommun: "Ludvika", region: "Dalarna" },
  "774": { city: "Avesta", kommun: "Avesta", region: "Dalarna" },
  "776": { city: "Hedemora", kommun: "Hedemora", region: "Dalarna" },
  "780": { city: "Sälen", kommun: "Malung-Sälen", region: "Dalarna" },
  "781": { city: "Borlänge", kommun: "Borlänge", region: "Dalarna" },
  "782": { city: "Malung", kommun: "Malung-Sälen", region: "Dalarna" },
  "783": { city: "Säter", kommun: "Säter", region: "Dalarna" },
  "784": { city: "Borlänge", kommun: "Borlänge", region: "Dalarna" },
  "785": { city: "Gagnef", kommun: "Gagnef", region: "Dalarna" },
  "786": { city: "Vansbro", kommun: "Vansbro", region: "Dalarna" },
  "791": { city: "Falun", kommun: "Falun", region: "Dalarna" },
  "792": { city: "Mora", kommun: "Mora", region: "Dalarna" },
  "793": { city: "Leksand", kommun: "Leksand", region: "Dalarna" },
  "794": { city: "Orsa", kommun: "Orsa", region: "Dalarna" },
  "795": { city: "Rättvik", kommun: "Rättvik", region: "Dalarna" },
  "796": { city: "Älvdalen", kommun: "Älvdalen", region: "Dalarna" },

  // ----- Norrland -----
  "801": { city: "Gävle", kommun: "Gävle", region: "Gävleborg" },
  "802": { city: "Gävle", kommun: "Gävle", region: "Gävleborg" },
  "803": { city: "Gävle", kommun: "Gävle", region: "Gävleborg" },
  "806": { city: "Gävle", kommun: "Gävle", region: "Gävleborg" },
  "810": { city: "Skutskär", kommun: "Älvkarleby", region: "Uppsala län" },
  "811": { city: "Sandviken", kommun: "Sandviken", region: "Gävleborg" },
  "813": { city: "Hofors", kommun: "Hofors", region: "Gävleborg" },
  "815": { city: "Tierp", kommun: "Tierp", region: "Uppsala län" },
  "820": { city: "Bollnäs", kommun: "Bollnäs", region: "Gävleborg" },
  "821": { city: "Bollnäs", kommun: "Bollnäs", region: "Gävleborg" },
  "822": { city: "Alfta", kommun: "Ovanåker", region: "Gävleborg" },
  "823": { city: "Kilafors", kommun: "Bollnäs", region: "Gävleborg" },
  "824": { city: "Hudiksvall", kommun: "Hudiksvall", region: "Gävleborg" },
  "825": { city: "Iggesund", kommun: "Hudiksvall", region: "Gävleborg" },
  "826": { city: "Söderhamn", kommun: "Söderhamn", region: "Gävleborg" },
  "827": { city: "Ljusdal", kommun: "Ljusdal", region: "Gävleborg" },
  "828": { city: "Edsbyn", kommun: "Ovanåker", region: "Gävleborg" },
  "829": { city: "Bergsjö", kommun: "Nordanstig", region: "Gävleborg" },
  "831": { city: "Östersund", kommun: "Östersund", region: "Jämtland" },
  "832": { city: "Frösön", kommun: "Östersund", region: "Jämtland" },
  "833": { city: "Strömsund", kommun: "Strömsund", region: "Jämtland" },
  "834": { city: "Brunflo", kommun: "Östersund", region: "Jämtland" },
  "836": { city: "Lit", kommun: "Östersund", region: "Jämtland" },
  "840": { city: "Ånge", kommun: "Ånge", region: "Västernorrland" },
  "841": { city: "Ånge", kommun: "Ånge", region: "Västernorrland" },
  "842": { city: "Sveg", kommun: "Härjedalen", region: "Jämtland" },
  "850": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "852": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "853": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "854": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "855": { city: "Njurunda", kommun: "Sundsvall", region: "Västernorrland" },
  "856": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "857": { city: "Sundsvall", kommun: "Sundsvall", region: "Västernorrland" },
  "860": { city: "Söråker", kommun: "Timrå", region: "Västernorrland" },
  "861": { city: "Timrå", kommun: "Timrå", region: "Västernorrland" },
  "862": { city: "Kvissleby", kommun: "Sundsvall", region: "Västernorrland" },
  "863": { city: "Sundsbruk", kommun: "Sundsvall", region: "Västernorrland" },
  "871": { city: "Härnösand", kommun: "Härnösand", region: "Västernorrland" },
  "872": { city: "Kramfors", kommun: "Kramfors", region: "Västernorrland" },
  "881": { city: "Sollefteå", kommun: "Sollefteå", region: "Västernorrland" },
  "882": { city: "Långsele", kommun: "Sollefteå", region: "Västernorrland" },
  "891": { city: "Örnsköldsvik", kommun: "Örnsköldsvik", region: "Västernorrland" },
  "893": { city: "Bjästa", kommun: "Örnsköldsvik", region: "Västernorrland" },
  "894": { city: "Själevad", kommun: "Örnsköldsvik", region: "Västernorrland" },
  "895": { city: "Bredbyn", kommun: "Örnsköldsvik", region: "Västernorrland" },
  "901": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "902": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "903": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "904": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "905": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "906": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "907": { city: "Umeå", kommun: "Umeå", region: "Västerbotten" },
  "910": { city: "Vännäs", kommun: "Vännäs", region: "Västerbotten" },
  "911": { city: "Vännäs", kommun: "Vännäs", region: "Västerbotten" },
  "912": { city: "Vilhelmina", kommun: "Vilhelmina", region: "Västerbotten" },
  "915": { city: "Robertsfors", kommun: "Robertsfors", region: "Västerbotten" },
  "920": { city: "Storuman", kommun: "Storuman", region: "Västerbotten" },
  "921": { city: "Lycksele", kommun: "Lycksele", region: "Västerbotten" },
  "922": { city: "Vindeln", kommun: "Vindeln", region: "Västerbotten" },
  "923": { city: "Storuman", kommun: "Storuman", region: "Västerbotten" },
  "930": { city: "Arjeplog", kommun: "Arjeplog", region: "Norrbotten" },
  "931": { city: "Skellefteå", kommun: "Skellefteå", region: "Västerbotten" },
  "932": { city: "Skellefteå", kommun: "Skellefteå", region: "Västerbotten" },
  "934": { city: "Kåge", kommun: "Skellefteå", region: "Västerbotten" },
  "936": { city: "Boliden", kommun: "Skellefteå", region: "Västerbotten" },
  "937": { city: "Burträsk", kommun: "Skellefteå", region: "Västerbotten" },
  "941": { city: "Piteå", kommun: "Piteå", region: "Norrbotten" },
  "942": { city: "Älvsbyn", kommun: "Älvsbyn", region: "Norrbotten" },
  "943": { city: "Öjebyn", kommun: "Piteå", region: "Norrbotten" },
  "945": { city: "Norrfjärden", kommun: "Piteå", region: "Norrbotten" },
  "951": { city: "Luleå", kommun: "Luleå", region: "Norrbotten" },
  "952": { city: "Kalix", kommun: "Kalix", region: "Norrbotten" },
  "953": { city: "Haparanda", kommun: "Haparanda", region: "Norrbotten" },
  "954": { city: "Gammelstad", kommun: "Luleå", region: "Norrbotten" },
  "955": { city: "Råneå", kommun: "Luleå", region: "Norrbotten" },
  "961": { city: "Boden", kommun: "Boden", region: "Norrbotten" },
  "971": { city: "Luleå", kommun: "Luleå", region: "Norrbotten" },
  "972": { city: "Luleå", kommun: "Luleå", region: "Norrbotten" },
  "973": { city: "Luleå", kommun: "Luleå", region: "Norrbotten" },
  "975": { city: "Luleå", kommun: "Luleå", region: "Norrbotten" },
  "977": { city: "Gällivare", kommun: "Gällivare", region: "Norrbotten" },
  "981": { city: "Kiruna", kommun: "Kiruna", region: "Norrbotten" },
  "982": { city: "Gällivare", kommun: "Gällivare", region: "Norrbotten" },
  "983": { city: "Malmberget", kommun: "Gällivare", region: "Norrbotten" },
  "984": { city: "Pajala", kommun: "Pajala", region: "Norrbotten" },
};

/* ---------- Regional fallback (1st digit) ----------
   Used when the 3-digit prefix is unknown so we always have a usable
   string for copy. Better to say "Storstockholm" than "138 36". */
const REGION_BY_FIRST_DIGIT: Record<string, PostalArea> = {
  "1": { city: "Storstockholm", region: "Stockholms län" },
  "2": { city: "Skåne", region: "Skåne" },
  "3": { city: "Halland och Småland", region: "Halland/Småland" },
  "4": { city: "Storgöteborg", region: "Västra Götaland" },
  "5": { city: "Västergötland", region: "Västra Götaland" },
  "6": { city: "Östergötland", region: "Östergötland" },
  "7": { city: "Mellansverige", region: "Bergslagen/Mälardalen" },
  "8": { city: "Norrland", region: "Norrland" },
  "9": { city: "Norrbotten", region: "Norrbotten" },
};

const DEFAULT_AREA: PostalArea = { city: "Sverige", region: "Sverige" };

export function lookupPostalArea(postcode: string): PostalArea {
  const norm = postcode.replace(/\s/g, "");
  if (!/^\d{5}$/.test(norm)) return DEFAULT_AREA;
  const prefix3 = norm.slice(0, 3);
  if (PREFIX_TABLE[prefix3]) return PREFIX_TABLE[prefix3];
  const first = norm[0];
  return REGION_BY_FIRST_DIGIT[first] ?? DEFAULT_AREA;
}

/** Pretty-printed postcode "138 36" instead of "13836". */
export function formatPostcode(postcode: string): string {
  const norm = postcode.replace(/\s/g, "");
  if (!/^\d{5}$/.test(norm)) return postcode;
  return `${norm.slice(0, 3)} ${norm.slice(3)}`;
}
